# Generated by Django 4.2.20 on 2025-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eId", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=40)),
            ],
        ),
    ]
